export default {
    OPEN_ADD_MOVIE_MODAL: 'OPEN_ADD_MOVIE_MODAL',
    OPEN_EDIT_MOVIE_MODAL: 'OPEN_EDIT_MOVIE_MODAL',
    OPEN_DELETE_MOVIE_MODAL: 'OPEN_DELETE_MOVIE_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
}
