export default {
    ['FETCH_MOVIES_BEGIN']: 'FETCH_MOVIES_BEGIN',
    ['FETCH_MOVIES_SUCCESS']: 'FETCH_MOVIES_SUCCESS',
    ['FETCH_MOVIES_ERROR']: 'FETCH_MOVIES_ERROR',
    ['SET_MOVIES_FILTER_GENRE']: 'SET_MOVIES_FILTER_GENRE',
    ['SET_MOVIES_FILTER_SORT_BY']: 'SET_MOVIES_FILTER_SORT_BY',
    ['SET_MOVIES_FILTER_SORT_ORDER']: 'SET_MOVIES_FILTER_SORT_ORDER',
}
